### ISSUE TITLE
Add error expectation with single point solutions

### ISSUE THREAD

**Issue by mas12498** [mas12498/tracker#1]
Need to adapt or expand output to include error sensitivity for input perturbation levels...

**Comment by caseyshields** [comment]
The MonteCarloTest in the error-bound branch is producing data. Can you make sense of it?

**Comment by caseyshields** [comment]
Between the Pedestal changes and your UI changes, I think this issue was resolved...
Can we close it?

**Comment by mas12498** [comment]
Looking forward to discuss face to face with you this weekend.
