### ISSUE TITLE
TestFilter Observations

### ISSUE THREAD

**Issue by mas12498** [mas12498/tracker#14]
Refactor TestFilter  to use the Observations interface.
This will let the filter be run on simulated, recorded or streaming data.

Also refactor TestFilter to use an ensemble instead of a pedestal array.
This will prevent duplication of some common tasks on sets of pedestals.

**Comment by caseyshields** [comment]
We need to remove the truth state from the observations and make it it's own thing. Unfortunately this is subtly different from the current parametric form of the Trajectory interface and I'm not sure how to reconcile the difference;

Trajectory tells you where you are given a time, and Observations simply reveals a sequence of measurements at points in time. A trajectory file therefore would not be able to tell you state at any point in time, but at only a few specific times...

One solution is making the parametric definition different from the sequence definition. Which is yet more interfaces and serializations to manage...

the other solution that comes to mind is shoe-horning the file reader into the trajectory interface, but it would probably mar the interface as well as require non intuitive use for the parametric definition(i.e. only a few valid query times or some interpolation which is a whole other can of worms..)

perhaps we need to change the trajectory interface; make the time sampling part of it's interface, so it becomes just another sequence...

Yup, I think that's the right solution; we haven't needed the full power of continuous parametric definitions and I don't believe it resembles any other measurement data we produce. Which obviously isn't good if you're trying to make them interchangeable.
